version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'   # AMQP protocol port
      - '15672:15672' # Management interface port
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq'
    networks:
      - backend

volumes:
  rabbitmq_data:

networks:
  backend:
    driver: bridge
